import { pgTable, text, timestamp, uuid, integer } from "drizzle-orm/pg-core";

export const activities = pgTable("activities", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), location: text("location"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const profiles = pgTable("profiles", { id: uuid("id").defaultRandom().primaryKey(), fullName: text("full_name").notNull(), role: text("role").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const patients = pgTable("patients", { id: uuid("id").defaultRandom().primaryKey(), fullName: text("full_name").notNull(), nik: text("nik").notNull(), phone: text("phone"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const visits = pgTable("visits", { id: uuid("id").defaultRandom().primaryKey(), patientId: uuid("patient_id").notNull(), status: text("status").notNull().default("waiting"), queueNumber: integer("queue_number"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const triageRecords = pgTable("triage_records", { id: uuid("id").defaultRandom().primaryKey(), visitId: uuid("visit_id").notNull(), priority: text("priority").notNull(), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const medicalRecords = pgTable("medical_records", { id: uuid("id").defaultRandom().primaryKey(), visitId: uuid("visit_id").notNull(), diagnosis: text("diagnosis").notNull(), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const medicines = pgTable("medicines", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), stock: integer("stock").notNull().default(0), createdAt: timestamp("created_at").defaultNow().notNull() });
export const prescriptions = pgTable("prescriptions", { id: uuid("id").defaultRandom().primaryKey(), visitId: uuid("visit_id").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const prescriptionItems = pgTable("prescription_items", { id: uuid("id").defaultRandom().primaryKey(), prescriptionId: uuid("prescription_id").notNull(), medicineId: uuid("medicine_id").notNull(), qty: integer("qty").notNull() });
export const referrals = pgTable("referrals", { id: uuid("id").defaultRandom().primaryKey(), visitId: uuid("visit_id").notNull(), facility: text("facility").notNull(), reason: text("reason").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const documents = pgTable("documents", { id: uuid("id").defaultRandom().primaryKey(), fileName: text("file_name").notNull(), fileUrl: text("file_url").notNull(), fileType: text("file_type").notNull(), fileSize: integer("file_size").notNull(), patientId: uuid("patient_id"), visitId: uuid("visit_id"), activityId: uuid("activity_id"), uploadedBy: uuid("uploaded_by"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), action: text("action").notNull(), actorId: uuid("actor_id"), entity: text("entity").notNull(), entityId: text("entity_id"), createdAt: timestamp("created_at").defaultNow().notNull() });
